#include "render/renderer.h"
#include "utils/logger.h"

#include <cmath>
#include <cstdlib>

Renderer Renderer::New(SDL_Window *win) {
    Renderer r;
    r.sdl_renderer = SDL_CreateRenderer(win, nullptr);
    if (!r.sdl_renderer) {
        logger::error("Renderer::New: SDL_CreateRenderer failed: %s", SDL_GetError());
        SDL_Quit();
        exit(1);
    }
    return r;
}

void Renderer::destroy() {
    SDL_DestroyRenderer(this->sdl_renderer);
    this->sdl_renderer = nullptr;
}

void Renderer::set_color(Color c) {
    SDL_SetRenderDrawColor(this->sdl_renderer, c.r, c.g, c.b, 255);
}

void Renderer::clear() {
    SDL_RenderClear(this->sdl_renderer);
}

void Renderer::plot(int x, int y) {
    SDL_RenderPoint(this->sdl_renderer, (float)x, (float)y);
}

void Renderer::draw_line(float x0, float y0, float x1, float y1) {
    SDL_RenderLine(this->sdl_renderer, (int)x0, (int)y0, (int)x1, (int)y1);
}

void Renderer::fill_rect(float x, float y, float w, float h) {
    SDL_FRect rect{x, y, w, h};
    SDL_RenderFillRect(this->sdl_renderer, &rect);
}

void Renderer::draw_rect(float x, float y, float w, float h) {
    SDL_FRect rect{x, y, w, h};
    SDL_RenderRect(this->sdl_renderer, &rect);
}

// INFO: Generated by Claude Sonnet 4.6
void Renderer::fill_column_aa(float x,
                              float w,
                              float y_top,
                              float y_bottom,
                              Color wall,
                              Color ceiling,
                              Color floor) {
    int top_solid = (int)ceilf(y_top);
    int bot_solid = (int)floorf(y_bottom);
    float top_frac = (float)top_solid - y_top;
    float bot_frac = y_bottom - floorf(y_bottom);

    Color top_c = ceiling.lerp(wall, top_frac);
    SDL_SetRenderDrawColor(this->sdl_renderer, top_c.r, top_c.g, top_c.b, 255);
    SDL_FRect top_row{x, (float)(top_solid - 1), w, 1.0f};
    SDL_RenderFillRect(this->sdl_renderer, &top_row);

    SDL_SetRenderDrawColor(this->sdl_renderer, wall.r, wall.g, wall.b, 255);
    SDL_FRect body{x, (float)top_solid, w, (float)(bot_solid - top_solid)};
    SDL_RenderFillRect(this->sdl_renderer, &body);

    Color bot_c = wall.lerp(floor, 1.0f - bot_frac);
    SDL_SetRenderDrawColor(this->sdl_renderer, bot_c.r, bot_c.g, bot_c.b, 255);
    SDL_FRect bot_row{x, (float)bot_solid, w, 1.0f};
    SDL_RenderFillRect(this->sdl_renderer, &bot_row);
}

// INFO: Generated by Claude Sonnet 4.6
void Renderer::draw_circle(float cx, float cy, float radius) {
    int x = (int)radius;
    int y = 0;
    int err = 0;
    int icx = (int)cx, icy = (int)cy;

    while (x >= y) {
        this->plot(icx + x, icy + y);
        this->plot(icx + y, icy + x);
        this->plot(icx - y, icy + x);
        this->plot(icx - x, icy + y);
        this->plot(icx - x, icy - y);
        this->plot(icx - y, icy - x);
        this->plot(icx + y, icy - x);
        this->plot(icx + x, icy - y);
        if (err <= 0) {
            y++;
            err += 2 * y + 1;
        }
        if (err > 0) {
            x--;
            err -= 2 * x + 1;
        }
    }
}

void Renderer::fill_circle(float cx, float cy, float radius) {
    for (float dy = -radius; dy <= radius; dy += 1.0f) {
        float dx = sqrtf(radius * radius - dy * dy);
        this->draw_line(cx - dx, cy + dy, cx + dx, cy + dy);
    }
}

void Renderer::present() {
    SDL_RenderPresent(this->sdl_renderer);
}
